# Generated by Django 5.0.6 on 2024-06-21 18:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0003_alter_post_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_date']},
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-create_date'], name='avito_post_create__72cc99_idx'),
        ),
    ]
