# Generated by Django 5.0.6 on 2024-06-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0004_alter_post_options_message_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
