# Generated by Django 5.0.6 on 2024-06-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0005_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата объявления'),
        ),
    ]
