# Generated by Django 5.0.6 on 2024-06-23 12:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0007_alter_message_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Дополнительные файлы'),
        ),
    ]
