# Generated by Django 5.0.6 on 2024-06-23 17:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0008_post_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Дополнительные файлы'),
        ),
    ]
