# Generated by Django 5.0.6 on 2024-06-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avito', '0009_alter_post_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
